version: '3.1'

services:
  api-server:
    build: .
    depends_on:
      - dev-postgres
    container_name: api-container
    tty: true
    ports:
      - 8080:8080
    environment:
      - GO_ENV=dev
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=dev-postgres
      - API_KEY=${API_KEY}
      - CLIENT_ID=${CLIENT_ID}
      - PORT=8080
      - FRONT_URL=${FRONT_URL}
    volumes:
      - ./:/app
  dev-postgres:
    container_name: db-container
    image: postgres:15.1-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always