name: test connection to render

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: test connection
        run: |
          curl https://ai-typing-api.onrender.com
